// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Navbar: typeof import('./components/Navbar/index.vue')['default']
    VarAppBar: typeof import('@varlet/ui')['_AppBarComponent']
    VarBadge: typeof import('@varlet/ui')['_BadgeComponent']
  }
}

export {}
