// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Header: typeof import('./components/Header/index.vue')['default']
    Navbar: typeof import('./components/Navbar/index.vue')['default']
    VirtualList: typeof import('./components/VirtualList/index.vue')['default']
  }
}

export {}
